apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
  namespace: amazon-cloudwatch
data:
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "devops-test",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }
